// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkwkwOd9gZXvNMRurV_D6FH9je8jDnwVQ',
    appId: '1:804788110223:web:400663246fef2ded4e01fa',
    messagingSenderId: '804788110223',
    projectId: 'your-health-mate',
    authDomain: 'your-health-mate.firebaseapp.com',
    storageBucket: 'your-health-mate.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYJvDxWm62vItjtlZTQtOkv4ASc2NvNDg',
    appId: '1:804788110223:android:0226580b0dae253b4e01fa',
    messagingSenderId: '804788110223',
    projectId: 'your-health-mate',
    storageBucket: 'your-health-mate.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD-e4tR33sl2FCh9fxMya7YUGGkaVWUAM',
    appId: '1:804788110223:ios:0fc47f4dffe817854e01fa',
    messagingSenderId: '804788110223',
    projectId: 'your-health-mate',
    storageBucket: 'your-health-mate.appspot.com',
    iosBundleId: 'com.example.yourHealthMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD-e4tR33sl2FCh9fxMya7YUGGkaVWUAM',
    appId: '1:804788110223:ios:0fc47f4dffe817854e01fa',
    messagingSenderId: '804788110223',
    projectId: 'your-health-mate',
    storageBucket: 'your-health-mate.appspot.com',
    iosBundleId: 'com.example.yourHealthMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkwkwOd9gZXvNMRurV_D6FH9je8jDnwVQ',
    appId: '1:804788110223:web:007d7cbcb77b296d4e01fa',
    messagingSenderId: '804788110223',
    projectId: 'your-health-mate',
    authDomain: 'your-health-mate.firebaseapp.com',
    storageBucket: 'your-health-mate.appspot.com',
  );
}
